leftnav:
- identifier: 9d34f88e-aabc-dc62-b425-4e0335c114e2
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 6ea9f202-90e1-5867-9830-5ee6186fc619
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 2501e907-9da1-5aef-9b0e-f0351c368cc4
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 852850cc-2457-2898-82b2-3964d31dc571
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 1ad10432-f179-6663-7995-5bdcb97b65ac
  name: Projects
  pageRef: /pages/projects
  weight: 50
